### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jivan84**
Hi, I have added a useful reference link, I think this will help your repository, Please merge it if find usefull. Thank you.

### CODE REVIEW

**Comment by MarkMoretto** [comment]
What's useful about the link?

**Comment by jivan84** [comment]
Hi @MarkMoretto, thanks for the response, I mean the link presents you with useful insights, covers necessary skills, highlights top machine learning career options, evaluates job prospects, and provides recommendations on how to start your career as a professional machine learning engineer.

**Comment by MarkMoretto** [comment]
Not really necessary, IMHO.  Just the same word garble rehashed, probably
copied from somewhere else.

Do you have a financial interest in Scaler?  You should disclose that, if
so.

The author is a self-described lifelong "technical writer
<https://www.linkedin.com/in/madhurihammad/>" with a selfie as a
professional profile photo, not someone who has worked in the industry.
What would they know about what it takes to become an ML engineer?

Just my $.02.

**Comment by jivan84** [comment]
Thanks for the offer man. But I don't have any financial interest.

**Pull request closed without merging**
